version: '3.1'
services:
  database:
    image: mysql
    container_name: hotel_oruro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_oruro_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
